services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: weiwei2003921124
      MYSQL_DATABASE: food_recipe
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./food101.sql:/docker-entrypoint-initdb.d/01_food101.sql:ro
      - ./food_recipe_dhr.sql:/docker-entrypoint-initdb.d/02_food_recipe_dhr.sql:ro
      - ./food_recipe_hr.sql:/docker-entrypoint-initdb.d/03_food_recipe_hr.sql:ro
      - ./food_recipe_nr.sql:/docker-entrypoint-initdb.d/04_food_recipe_nr.sql:ro

  web:
    build:
      context: .
    container_name: flask_app
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASSWORD: weiwei2003921124
      DB_HOST: mysql
      DB_NAME: food_recipe
    ports:
      - "10443:5000"
    # volumes:
    #   - .:/app
    command: python app.py

volumes:
  mysql_data:

