-- MySQL dump 10.13  Distrib 8.0.36, for Win64 (x86_64)
--
-- Host: localhost    Database: food_recipe
-- ------------------------------------------------------
-- Server version	8.0.36

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `hr`
--

DROP TABLE IF EXISTS `hr`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `hr` (
  `title` text,
  `ingredients` json DEFAULT NULL,
  `directions` json DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `hr`
--

LOCK TABLES `hr` WRITE;
/*!40000 ALTER TABLE `hr` DISABLE KEYS */;
INSERT INTO `hr` VALUES
('apple_pie','[\"1 (6 oz.) can (3/4 c.) unsweetened frozen apple juice concentrate\", \"1 tsp. cinnamon\", \"2 tsp. margarine\", \"2 Tbsp. Minute tapioca\", \"1 tsp. nutmeg\"]','[\"In saucepan, cook ingredients, stirring constantly until thick.\", \"Add 6 apples, peeled and sliced.\", \"Put into two crust pie shell and bake at 375° for one hour or usual timing for two crust pie.\"]'),
('beet_salad','[\"1 (15 1/2 oz.) can crushed pineapple (save the juice)\", \"1 (15 1/2 oz.) can beets (diced, sliced or chopped; save the juice)\", \"1/4 c. lemon juice\", \"1/4 c. vinegar\", \"1 large raspberry jello\", \"1 Tbsp. sugar\", \"1/2 c. chopped nuts\"]','[\"Drain the pineapple and beets, saving the juice.\", \"Add lemon juice, vinegar and enough water added to the juice to make 3 1/2 cups liquid.\", \"Heat.\", \"Add the sugar and jello, stirring until completely dissolved; cool.\", \"Add cut up beets, pineapple and nuts. Pour into a large (9 x 13-inch or more) pan.\", \"Chill until set. Serve on lettuce with a little mayonnaise, if desired.\"]'),
('bread_pudding','[\"4 c. cubed (3/4-inch) French bread\", \"1/2 c. raisins\", \"3 c. 1% milk, divided\", \"3 Tbsp. packed brown sugar, divided\", \"pinch of salt\", \"1 large egg\", \"2 large egg whites\", \"1/3 c. sugar\", \"1 tsp. vanilla\", \"1/4 tsp. nutmeg\", \"1/2 tsp. cinnamon\", \"boiling water\"]','[\"Preheat oven to 350°.\", \"In an 8-inch pan, spread bread and raisins.\", \"Whisk 2 cups\", \"of milk, 2 tablespoons brown sugar and salt in bowl.\", \"Pour over bread.\", \"Let stand 15 minutes, turning bread once.\"]'),
('bruschetta','[\"1 c. nonfat process cream cheese\", \"1/4 c. plus 2 Tbsp. nonfat sour cream\", \"2 Tbsp. reduced calorie mayonnaise\", \"1 c. finely shredded low sodium fat Swiss cheese, divided\", \"1/4 c. finely grated fresh Parmesan cheese\", \"2 Tbsp. minced parsley\", \"1 Tbsp. minced green onion\", \"2 cloves garlic, minced\", \"16 (1-inch) diagonally cut slices French bread, toasted\", \"1/4 tsp. pepper\"]','[\"Combine first 3 ingredients in a bowl; beat at medium speed of electric mixer until smooth.\", \"Stir in 1/2 cup of Swiss cheese, Parmesan cheese and next 3 ingredients.\", \"Spread cheese mixture evenly over toast slices; sprinkle evenly with remaining 1/2 cup Swiss cheese.\", \"Broil for 1 1/2 minutes or until Swiss cheese melts.\", \"Sprinkle with pepper.\", \"Yield:\", \"16 servings.\"]'),
('caesar_salad','[\"2 (1 oz.) slices white bread\", \"olive oil flavored spray\", \"1/2 tsp. garlic powder\", \"1 clove garlic, halved\", \"4 c. shredded romaine lettuce\", \"1/3 c. no salt added chicken broth\", \"3 Tbsp. lemon juice\", \"2 tsp. low sodium Worcestershire sauce\", \"1 tsp. anchovy paste\", \"1/4 tsp. dry mustard\", \"3 Tbsp. freshly grated Parmesan cheese\", \"1/2 tsp. cracked pepper\"]','[\"Coat one side of each slice of bread lightly with cooking spray.\", \"Sprinkle evenly with garlic powder.\", \"Place on ungreased baking sheet.\", \"Bake at 300° for 18 to 20 minutes.\", \"Cut into cubes and set aside.\", \"Rub inside of a large salad bowl with garlic. Place lettuce in bowl.\", \"Combine chicken broth, lemon juice, Worcestershire, anchovy and mustard in a small bowl, stirring well. Drizzle over lettuce.\", \"Sprinkle salad with Parmesan cheese and cracked pepper.\", \"Toss well.\", \"Top with bread cubes.\", \"Serve immediately.\", \"Contains 82 calories, 27% from fat per 1 cup serving.\"]'),
('carrot_cake','[\"1 c. ground carrots\", \"1 c. raisins\", \"1 c. walnuts\", \"3 Tbsp. margarine\", \"1 1/2 c. water\", \"1 tsp. cinnamon\", \"1 tsp. cloves\", \"1 tsp. nutmeg\", \"2 c. flour\", \"2 tsp. soda\", \"1/2 tsp. salt\"]','[\"Mix the first eight ingredients.\", \"Heat to boil and then simmer 5 minutes.\", \"Cool to warm and add flour, soda and salt.\", \"Mix well. Bake in a greased and floured 9 x 13-inch pan 45 to 60 minutes at 325° or until done.\"]'),
('cheesecake','[\"8 oz. pkg. nonfat or reduced fat cream cheese\", \"8 oz. nonfat sour cream\", \"1 Tbsp. nonfat or low-fat yogurt\", \"1 Tbsp. water\", \"1 pkg. instant pudding (no sugar)\", \"1 prepared graham cracker crust\"]','[\"Soften cream cheese.\", \"Combine first 4 ingredients in blender (or bowl) and blend thoroughly.\", \"In large bowl, add instant pudding to blended mixture and mix with spoon quickly until powder is incorporated.\", \"This step must be done by hand.\", \"Spoon into prepared crust and smooth top.\", \"Refrigerate several hours to firm. Garnish with fruit, if desired.\"]'),
('chicken_curry','[\"2 c. cooked, diced chicken\", \"1/2 lb. thinly sliced fresh mushrooms\", \"1 Tbsp. oil or margarine\", \"1/3 c. chopped onion\", \"3 Tbsp. flour\", \"1 c. chicken broth\", \"1 1/2 tsp. curry powder\", \"1 c. chopped apple\", \"1/4 c. chopped parsley\", \"3/4 c. skim milk\", \"1 c. water\"]','[\"In a large skillet, saute chicken, mushrooms and onions in oil until chicken is lightly browned on all sides.\", \"Stir in flour, broth and curry powder.\", \"Add apple and parsley, then pour milk and water.\", \"Simmer, stirring constantly, for 3 minutes or until apple pieces are tender and crisp.\", \"Serve over rice.\", \"Makes 4 to 6 servings.\", \"Calories per serving: 235 (or 335 with 1/2 cup rice).\"]'),
('chocolate_cake','[\"1 c. flour\", \"1/3 c. plus 1 Tbsp. unsweetened cocoa powder\", \"1 tsp. instant Espresso powder\", \"1 tsp. baking powder\", \"1 tsp. baking soda\", \"6 large egg whites\", \"1 tsp. vanilla\", \"1 1/3 c. firmly packed golden brown sugar\", \"1 c. coffee flavored nonfat yogurt\"]','[\"Preheat oven to 350°.\", \"Line bottom of a 9-inch cake pan with waxed\", \"paper.\", \"Spray pan and paper with vegetable oil spray.\", \"Dust pan with flour.\"]'),
('chocolate_mousse','[\"1 (12 oz.) pkg. semi-sweet chocolate pieces\", \"1/2 c. boiling water\", \"2 tsp. Angostura aromatic bitters\", \"3 egg yolks\", \"4 egg whites\"]','[\"Combine chocolate pieces, boiling water, Angostura and egg yolks in blender.\", \"Whirl until smooth.\", \"Cool to room temperature. Beat egg whites in bowl until stiff.\", \"Fold in chocolate mixture. Spoon mixture into serving dishes; chill for several hours.\", \"Serve with demi-tasse.\", \"Contains 265 calories per serving.\"]'),
('clam_chowder','[\"2 cans clams\", \"2 bay leaves\", \"1 Tbsp. oregano\", \"1/2 c. chopped onion\", \"4 c. low-fat chicken broth\", \"2 medium carrots, sliced\", \"2 medium potatoes, diced\", \"1 c. cut green beans\", \"1 Tbsp. parsley\", \"1 Tbsp. tarragon\", \"1/4 tsp. black pepper\"]','[\"In a large saucepan, cook all ingredients except clams, about 20 minutes or until vegetables are tender. Add clam juice and cook 5 minutes more.\", \"Remove from heat and add clams.\", \"Has only about 3 grams fat.\"]'),
('deviled_eggs','[\"6 hard-boiled eggs\", \"1/4 c. creamed cottage cheese\", \"2 Tbsp. skim milk\", \"1/2 tsp. cream-style horseradish\"]','[\"Halve eggs lengthwise.\", \"Remove yolks and mash yolks.\", \"Add cottage cheese, skim milk and horseradish; mix well.\", \"Then return to halved egg whites.\", \"Top with sprinkle of paprika or dry minced parsley.\", \"Makes 12 servings.\", \"One serving equals 48 calories or 1 lean meat exchange.\"]'),
('eggs_benedict','[\"2 oz. shredded low-fat Cheddar cheese\", \"2/3 c. nonfat dry milk\", \"1/2 c. water\", \"1/4 tsp. dry mustard\", \"1 Tbsp. imitation bacon bits\", \"1 English muffin, split and toasted\", \"2 eggs, poached\"]','[\"In the top of a double boiler over boiling water, combine cheese, dry milk, water and mustard.\", \"Cook, stirring, until cheese is melted.\", \"Sprinkle bacon bits evenly on English muffin halves. Top each half with a poached egg; spoon sauce over eggs.\", \"Serves 2.\"]'),
('french_fries','[\"2 large potatoes\", \"olive oil flavored nonstick spray\", \"3 Tbsp. grated Parmesan cheese\", \"1/4 tsp. paprika\"]','[\"Cut potatoes lengthwise into thin wedges.\", \"Place in a plastic bag.\", \"Spray wedges lightly with coating.\", \"Add Parmesan cheese and paprika to bag; toss to coat wedges.\"]'),
('french_onion_soup','[\"3 medium onions, sliced\", \"1 Tbsp. flour\", \"2 cans Swanson beef broth, defatted\", \"1 c. water\", \"2 tsp. Molly McButter\", \"1/4 c. red cooking wine\", \"1/2 tsp. salt (optional)\", \"black pepper to taste\", \"6 slices sourdough bread, toasted\", \"6 slices Borden fat-free Swiss cheese\"]','[\"Preheat oven to 375°.\", \"In a large skillet sprayed with nonstick cooking spray, brown onions until golden brown.\", \"Sprinkle flour over onions and continue browning and stirring.\", \"In a medium saucepan, combine beef broth, water, Molly McButter, wine, salt and black pepper.\", \"Add onions and simmer 15 to 20 minutes.\", \"Pour soup into individual bowls; top with 1 slice of toast and 1 slice of cheese.\", \"Warm at 375° until cheese starts to melt.\", \"Serve immediately.\", \"Recipe makes 6 servings.\"]'),
('french_toast','[\"1 (8 oz.) carton Egg Beaters (1 c.)\", \"1/3 c. skim milk\", \"1 tsp. ground cinnamon\", \"1 tsp. vanilla extract\", \"2 Tbsp. liquid Butter Buds\", \"10 slices white bread (Wonder fat-free)\", \"lite maple syrup\"]','[\"In a shallow pan or bowl, combine Egg Beaters, milk, cinnamon and vanilla.\", \"In a nonstick skillet, over medium heat in liquid Butter Buds, place the pieces of bread after they have been dipped in the Egg Beater mixture. Brown about 3 minutes on each side. Add more liquid Butter Buds, if needed.\", \"Serve with lite maple syrup.\"]'),
('fried_rice','[\"6 c. steamed white rice (better if cooked in an electric rice cooker)\", \"1 c. frozen mixed vegetables\", \"2 eggs\", \"1 c. chopped lean cooked ham\", \"2 Tbsp. olive oil, divided\", \"3/4 Tbsp. soy sauce\", \"1/2 tsp. fish sauce\", \"1/2 tsp. garlic powder\", \"1/8 tsp. pepper\", \"1/4 tsp. sugar\", \"1 tsp. sesame oil\"]','[\"Keep the rice hot in the rice cooker.\", \"Thaw the mixed vegetables; drain and make sure they are diced and ready to use. Scramble eggs and fry in 1/2 tablespoon of olive oil in a nonstick pan.\", \"Spread evenly and lightly like a pancake.\", \"When done, dice them and set aside.\", \"Chop the cooked ham.\", \"If raw, precook in the microwave and drain.\"]'),
('frozen_yogurt','[\"1 envelope plain gelatin\", \"1/4 c. water\", \"2 c. evaporated skim milk\", \"1/2 c. plus 2 tsp. granulated fructose, divided\", \"1/4 tsp. salt\", \"32 oz. nonfat yogurt\", \"2 Tbsp. vanilla\", \"1 pt. strawberries\", \"1/4 c. skim milk\"]','[\"In a large saucepan, soften gelatin in water for 2 minutes. Place over medium heat until gelatin is dissolved.\", \"Add evaporated milk, 1/2 cup of the fructose and salt to gelatin.\", \"Stir over medium heat until well blended, approximately 5 minutes.\", \"Remove from heat.\", \"Stir in yogurt and vanilla.\", \"Set aside.\"]'),
('greek_salad','[\"12 medium shrimp\", \"1/2 c. + 2 Tbsp. olive oil\", \"2 cloves garlic, minced\", \"1 tsp. coarse salt, separated\", \"1/2 tsp. pepper, separated\", \"1/4 c. lemon juice\", \"1/2 tsp. dried oregano\", \"1 head romaine lettuce, washed and cut crosswise into 1 inch strips\", \"1 large tomato, cut into wedges\", \"2 small cucumbers, peeled and cut into large chunks\", \"1 small red onion, thinly sliced\", \"1/4 lb. black olives\"]','[\"12 medium shrimp\", \"1/2 c. + 2 Tbsp. olive oil\", \"2 cloves garlic, minced\", \"1 tsp. coarse salt, separated\", \"1/2 tsp. pepper, separated\", \"1/4 c. lemon juice\", \"1/2 tsp. dried oregano\", \"1 head romaine lettuce, washed and cut crosswise into 1 inch strips\", \"1 large tomato, cut into wedges\", \"2 small cucumbers, peeled and cut into large chunks\", \"1 small red onion, thinly sliced\", \"1/4 lb. black olives\"]'),
('guacamole','[\"1 mashed rip avocado\", \"1/2 cup non-fat yogurt plain\", \"1/2 teaspoon sugar\", \"2 tablespoons salsa\"]','[\"Mix together and serve with baked tortillas or veggies.\"]'),
('huevos_rancheros','[\"nonfat tortilla shells\", \"nonfat refried beans\", \"nonfat Cheddar cheese\", \"egg\", \"nonfat sour cream\", \"green pepper\", \"green onion\", \"salsa\"]','[\"Cover tortilla with 1/2 cup nonfat refried beans (heated), 1/2 cup nonfat Cheddar cheese, 1 fried egg white, 2 tablespoons salsa, 1/4 cup nonfat sour cream and 1/2 cup nonfat Cheddar cheese.\", \"Put in preheated oven at 350° until cheese melts.\", \"Top with 2 tablespoons green pepper and 1 chopped green onion.\", \"Serves one.\"]'),
('ice_cream','[\"1 small box vanilla sugar-free Jell-O pudding mix\", \"6 pkg. sweetener\", \"1 tsp. vanilla\", \"3 c. 2% milk\", \"pinch of salt\"]','[\"Mix all ingredients well.\", \"Pour into 1/2 gallon ice cream freezer; fill to freeze level with 2% milk and freeze.\"]'),
('lasagna','[\"1/2 lb. ground turkey\", \"1/2 tsp. garlic salt\", \"1 (30 oz.) jar Prego sauce (I use tomato/basil)\", \"3/4 c. water\", \"1 (8 oz.) pkg. lasagna noodles, cooked\", \"1 (11 oz.) container fat-free Ricotta cheese\", \"1 Tbsp. chopped parsley\", \"1 (8 oz.) pkg. fat-free Mozzarella cheese\"]','[\"Heat oven to 375°.\", \"Brown ground turkey.\", \"Add garlic salt, Prego and water.\", \"Bring to boil and remove from heat.\", \"In 9 x 13-inch glass dish, layer 1/3 of sauce, 1/2 of uncooked lasagna noodles, 1/2 of Ricotta cheese and 1/2 of Mozzarella.\", \"Sprinkle with parsley.\", \"Repeat layers, ending with sauce.\", \"Cover tightly with foil.\", \"Bake 1 hour.\", \"Uncover; sprinkle with Parmesan cheese if desired.\", \"Let stand 10 minutes before serving.\"]'),
('macaroni_and_cheese','[\"2 qt. water\", \"8 tsp. low-sodium chicken bouillon\", \"8 oz. tube pasta\", \"1/2 lb. smoked ham, thinly sliced and cut into 1/2-inch strips\", \"1 c. 2% milk\", \"1 c. nonfat milk\", \"2/3 c. liquid egg substitute\", \"1 Tbsp. unbleached all-purpose flour\", \"1/4 tsp. salt\", \"1/4 tsp. freshly ground pepper\", \"3 oz. reduced fat sharp Cheddar cheese, grated (3/4 c.)\", \"1 oz. Parmesan cheese, freshly grated (1/4 c.)\"]','[\"Preheat oven to 350°.\", \"In a large pot, bring water and bouillon to a boil. Add pasta and boil 8 minutes or until just done; drain well. Spray a 9 x 13-inch glass baking dish with nonstick vegetable oil.\", \"Place half the pasta in dish and cover with half of the ham strips.\", \"Repeat with the remaining pasta and ham.\", \"Combine milk, egg substitute, flour, salt and pepper; pour over pasta and ham.\", \"Sprinkle with both cheeses and bake about 30 minutes or until custard is set and casserole is lightly browned. Makes 8 servings.\"]'),
('nachos','[\"4 c. baked tortilla chips\", \"1 c. grated fat-free Mozzarella cheese\", \"1/2 c. fat-free sour cream\", \"1/2 c. minced canned green chilies\", \"2 Tbsp. minced fresh cilantro (optional)\"]','[\"Preheat broiler.\", \"Arrange tortilla chips on a nonstick baking pan.\", \"In a small bowl, stir together remaining ingredients.\", \"Spoon over chips.\", \"Broil nachos until brown and bubbling, about 5 minutes.\", \"Serve immediately.\", \"Serves 4 to 6.\"]'),
('onion_rings','[\"2 large sweet onions\", \"1 (7 oz.) pkg. corn flakes cereal, crushed\", \"1 tsp. seasoned salt\", \"2 tsp. sugar\", \"2 tsp. paprika\", \"1 c. egg substitute\", \"vegetable cooking spray\"]','[\"Cut each onion into 4 thick slices; separate into rings (reserve small rings for another use).\", \"Set aside.\", \"Combine cereal and next 3 ingredients; divide in half and set aside.\", \"Beat egg substitute at high speed with an electric mixer until soft peaks form.\", \"Dip half of onion rings in egg substitute; dredge in half of crumb mixture.\", \"Place in a single layer on baking sheets coated with cooking spray.\", \"Repeat procedure with remaining onion rings, egg substitute and crumb mixture.\", \"Bake at 375° for 15 minutes, or until crisp.\", \"Serve warm.\"]'),
('paella','[\"1 Tbsp. olive oil\", \"1/2 lb. chicken breast cubes\", \"1 c. uncooked long-grain white rice*\", \"1 medium onion, chopped\", \"1 clove garlic, minced\", \"1 1/2 c. chicken broth *\", \"1 (8 oz.) can stewed tomatoes, chopped (reserving liquid)\", \"1/2 tsp. paprika\", \"1/8 to 1/4 tsp. ground red pepper\", \"1/8 tsp. ground saffron\", \"1/2 lb. medium shrimp, peeled and deveined\", \"1 small red pepper, cut into strips\", \"1 small green pepper, cut into strips\", \"1/2 c. frozen green peas\"]','[\"Heat oil in Dutch oven over medium-high heat until hot.\", \"Add chicken and stir until browned.\", \"Add rice, onion and garlic. Cook, stirring, until onion is tender and rice is lightly browned. Add broth, tomatoes, tomato liquid, paprika, ground red pepper and saffron.\", \"Bring to a boil over high heat; stir.\", \"Reduce heat to low.\", \"Cover and simmer 10 minutes.\", \"Add shrimp, pepper strips and peas.\", \"Cover and simmer 10 minutes or until rice is tender, liquid is absorbed and shrimp are opaque.\"]'),
('pancakes','[\"2 eggs\", \"2 c. flour\", \"1 3/4 c. nonfat milk\", \"2 tsp. vanilla (optional)\", \"2 Tbsp. sugar (optional)\", \"2 Tbsp. baking powder\", \"1/2 tsp. salt\"]','[\"Beat eggs until fluffy; beat in remaining ingredients until smooth.\", \"Spray pan with Pam and cook to desired doneness.\", \"More milk may be added for thinner pancake batter.\"]'),
('pizza','[\"2 pkg. Martha White pizza crust mix\", \"1/2 c. pizza sauce\", \"1 1/2 c. light or low-fat Mozzarella cheese\", \"1/2 c. sliced mushrooms\", \"1/4 c. sliced banana peppers\", \"1 c. turkey pastrami, chopped\", \"1 c. ground turkey burgers\", \"Pam cooking spray\"]','[\"Prepare pizza crust according to package, except do not add cooking oil.\", \"Instead, spray dough with cooking spray.\", \"Prepare crust in pizza pan sprayed with cooking spray.\", \"First, spread sauce, then add cheese, then add remaining toppings.\", \"Preheat oven to 500°.\", \"Place pizza on lowest oven rack and cook 12 to 15 minutes.\", \"Enjoy!\"]'),
('pork_chop','[\"6 half cut pork chops\", \"1 can fat-free sweet and sour sauce\", \"dash of salt\", \"pepper to taste\"]','[\"Foil line a 9 x 13 pan or baking dish. Place chops flat and pour the sauce evenly over meat, adding enough water to cover, if necessary. Bake at 400° about 1 hour, until tender. If you like, you may brown by turning on broiler for about 5 minutes.\"]'),
('red_velvet_cake','[\"1/2 c. butter, softened\", \"4 oz. fat-free cream cheese, softened\", \"1 1/2 c. sugar\", \"1/2 c. egg substitute\", \"2 (1 oz.) bottles liquid red food coloring\", \"2 1/4 c. sifted cake flour\", \"2 Tbsp. unsweetened cocoa\", \"1 tsp. baking soda\", \"1/4 tsp. salt\", \"1 c. nonfat buttermilk\", \"1 tsp. vanilla extract\", \"vegetable cooking spray\", \"Boiled Frosting\"]','[\"Beat butter and cream cheese at medium speed until creamy. Gradually add sugar, beating well. Gradually add egg substitute, beating well. Stir in food coloring.\", \"Combine flour and next 3 ingredients.\", \"Add to butter mixture alternately with buttermilk, beginning and ending with flour mixture.\", \"Mix until just blended after each addition.\", \"Stir in vanilla.\", \"Pour batter into three 9-inch cake pans coated with cooking spray.\", \"Bake at 350° for 18 minutes.\", \"Cool in pans on wire racks for 10 minutes. Remove from pans.\", \"Cool completely on wire racks. Spread Boiled Frosting between layers, on sides and top of cake.\"]'),
('risotto','[\"1 medium chopped onion\", \"1 c. uncooked rice\", \"2 Tbsp. vegetable oil\", \"1/2 c. chopped green pepper\", \"2 c. sliced mushrooms\", \"1/2 c. frozen corn\", \"2 c. bouillon or broth\"]','[\"Cook onion\", \"and\", \"rice\", \"in\", \"the\\t2\", \"tablespoons oil over medium heat\", \"until\", \"golden,\", \"stirring\", \"constantly.\", \"Add green pepper and mushrooms\\tand cook 2 minutes.\", \"Stir in the frozen corn and the bouillon\", \"or broth.\", \"Bring to boil; stir once or twice.\", \"Reduce heat; cover and simmer 15 minutes or until rice is tender\", \"and liquid\", \"is\\tabsorbed.\", \"Toss lightly with fork. Sprinkle with grated Parmesan cheese, if desired.\", \"You can add leftover cut up chicken and water chestnuts (if desired) for a main\", \"dish.\\tYou can\", \"also\", \"add\", \"any\", \"combination\", \"of\", \"herbs: rosemary, parsley, basil or marjoram.\"]'),
('scallops','[\"1 lb. scallops\", \"1 Tbsp. vegetable oil\", \"1 garlic clove, minced\", \"2 medium tomatoes, halved\", \"pepper\", \"salt\", \"1 1/2 Tbsp. lemon juice\", \"1 Tbsp. melted margarine\", \"lemon twists (for garnish)\", \"chopped parsley (for garnish)\"]','[\"About 50 minutes before serving, let scallops stand in oil and garlic for 30 minutes.\", \"Preheat broiler 10 minutes.\", \"Meanwhile, sprinkle tomato halves with pepper and 1/2 teaspoon salt.\", \"In shallow roasting pan, arrange with scallops.\", \"Over scallops pour margarine, 1/2 teaspoon salt, lemon juice and 1/8 teaspoon pepper. Broil about 10 minutes, turning once.\", \"Serve garnished with lemon twists and parsley.\"]'),
('steak','[\"1 Tbsp. flour\", \"3/4 tsp. salt\", \"dash of pepper\", \"1 lb. lean round steak\", \"1 Tbsp. margarine\", \"16 oz. canned tomatoes\", \"1 1/2 c. sliced onion\", \"1/3 c. diced celery\", \"1 clove garlic, crushed\", \"1/2 tsp. sugar\"]','[\"Combine flour, salt and pepper.\", \"Cut steak into four pieces. Pound flour mixture into steak.\", \"In heavy skillet, melt margarine. Add meat and brown on both sides.\", \"Add remaining ingredients. Reduce heat and simmer for one hour.\", \"Serves 4, 315 calories per serving.\"]'),
('strawberry_shortcake','[\"1 3/4 angel food cakes, sliced in thirds\", \"4 containers no fat strawberry yogurt\", \"1 1/2 containers fat-free Cool Whip\", \"1 large can crushed pineapple, drained\", \"1 1/2 qt. sliced strawberries\", \"1/2 c. slivered almonds\"]','[\"Make the following layers:\", \"cake, Cool Whip, cake, yogurt, cake, nuts, cake, pineapple and top with strawberries.\"]'),
('tacos','[\"1 lb. extra lean ground beef\", \"1 pkg. taco mix\", \"1 doz. (6-inch) flour tortillas\", \"8 oz. grated reduced-fat Cheddar\", \"shredded lettuce\", \"chopped tomatoes\", \"chopped onions (if desired)\", \"non-fat sour cream (optional)\"]','[\"Brown meat, then rinse in a colander under hot water.\", \"Let drain.\", \"Return meat to pan, add taco mix and follow instructions on mix package to prepare taco meat.\", \"Steam tortillas, and assemble tacos.\", \"Makes about 6 to 8 tacos.\"]'),
('tiramisu','[\"18 ladyfingers (about 4 1/2 oz.)\", \"2 tsp. Dutch processed cocoa powder\", \"3/4 c. fat-free or light whipped topping (optional)\"]','[\"To assemble the desserts, coarsely crumble 1 1/2 ladyfingers into the bottom of each of six (10 oz.) balloon wine glasses.\", \"Top the ladyfingers with 1 tablespoon of the coffee mixture, and 1/4 cup of the custard.\", \"Repeat the layers.\", \"Then sift a little cocoa over the top of each dessert.\", \"Cover the desserts and refrigerate for at least 2 hours.\", \"If desired, top each serving with 2 tablespoons of the whipped topping just before serving.\"]'),
('waffles','[\"3/4 c. egg substitute\", \"1 1/2 c. skim milk\", \"1/3 c. safflower oil\", \"2 c. all-purpose flour\", \"2 tsp. baking powder\", \"2 tsp. sugar\", \"1/2 tsp. or less salt\"]','[\"Whirl eggs in blender; add milk and oil.\", \"Blend 2 minutes; add dry ingredients and whirl.\", \"Bake in preheated Teflon waffle iron. Makes 4 large waffles.\"]');
/*!40000 ALTER TABLE `hr` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2025-06-20 12:00:15
